config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#GoogleAuth'
  get '/auth/failure' => 'sessions#new'
  

  resources :reviews
  resources :categories
  resources :podcasts do
    get :most_recent, on: :collection
    resources :reviews, only: [:new, :index, :create]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :podcasts
end

app/models/podcast.rb
class Podcast < ApplicationRecord
    before_create :set_id

    
    scope :most_recent, -> { limit(10).order('created_at DESC') }   
    has_many :reviews
    has_many :user_reviews, through: :reviews, source: :user

    has_many :users_podcasts
    has_many :podcast_reviews, through: :users_podcasts, source: :podcast

    belongs_to :category

    private

def set_id
  self.id = Podcast.last.id + 1 
end

end 

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :podcast

  validates :stars, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 6}

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :podcast_reviews, through: :reviews, source: :podcast

    has_many :users_podcasts
    has_many :user_reviews, through: :reviews, source: :user

    has_secure_password

    validates :username, uniqueness: true, presence: true
end

app/models/userpodcasts.rb
class UserPodcasts < ApplicationRecord
    belongs_to :user
    belongs_to :podcast
end
      

app/models/users_podcast.rb
class UsersPodcast < ApplicationRecord
    belongs_to :user
    belongs_to :podcast
end
      

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def after_sign_in_path_for(resource)
        # user_path(current_user) # your path
        podcasts_path
    end
  
    def current_user
      User.find(session[:user_id]) rescue nil
    end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :get_category, only: [:show]
   
   
    def index
        @categories = Category.all
        @podcasts = Podcast.all
    end 

   def show
       @podcasts = @category.podcasts.all
    end


    private 


        def get_category
            @category = Category.find(params[:id])
        end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  def new
    @podcast = Podcast.new
  end

  def create
      if params[:podcast][:id].present?
        @podcast = Podcast.find_by(id: params[:podcast][:id])
      else
        @podcast = Podcast.find_or_create_by(podcast_params) # if it is not present, then they want to create a new one, use find or create so it doesn't make duplicates
        UsersPodcast.create!(user: current_user, podcast: @podcast)
      end

      redirect_to podcast_path(@podcast)
    end


  def show

    @podcast = Podcast.find(params[:id])

  end

  def most_recent
      @podcasts = Podcast.most_recent
  end

  def index
    @podcasts = Podcast.all
  end

private

def podcast_params
  params.require(:podcast).permit(:name, :author, :description, :category_id)
end

  # def logged_in_user
  #   unless logged_in?
  #     store_location
  #     flash[:danger] = "Please log in."
  #     redirect_to login_url
  #   end
  # end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
  
  
    def new
      if @podcast = Podcast.find_by_id(params[:podcast_id])
        @review = @podcast.reviews.build
      else
        @review = Review.new
      end
    end
  
    def create

      @review = current_user.reviews.build(review_params)
      if @review.save
        redirect_to podcast_path(@review.podcast)
      else
        render :new
      end
    end
  
    def show
      @review = Review.find_by_id(params[:id])
    end
  
    def index
      #how do i check if it's nested & a valid id
      if @podcast = Podcast.find_by_id(params[:podcast_id])
        #nested
        @reviews = @podcast.reviews
      else
        #it's not nested
        @reviews = Review.all
      end
    end
  
    private
  
    def review_params
        params.require(:review).permit(:podcast_id, :description, :stars, :title)
    end
  
  
  
  
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def welcome
end

def destroy
    session.delete :user_id
    redirect_to '/'
end 


def new
end

def create
        user = User.find_by(username: params[:username])
        if user && user.authenticate(params[:password])
        session[:user_id] = user.id
       redirect_to user_path(user)
    else 
        flash[:error] = "Sorry, your login info is incorrect. Please try again."
        redirect_to login_path
    end 
end 


def GoogleAuth
    access_token = request.env["omniauth.auth"]
    user = User.from_omniauth(access_token)
    if user.present? 
        session[:user_id] = user.id 
        redirect_to user_path(user)
    else   
     
        redirect login_path
    end
end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end 
    end 

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user

    end 

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      User.find(session[:user_id]) rescue nil
    end
  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1> Podcast Categories </h1>

<ul>
<% @categories.each do |category| %>
     <li> <%= category.name %> </li>
     <ul>
     <% category.podcasts.each do |podcast| %>
          <li><a href="<%= podcast_path(podcast)  %>"><%= podcast.name %></a> </li>
     <% end %>
     </ul>
<% end %>

</ul>

<%= link_to 'Most Recent Podcasts', most_recent_podcasts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podcastapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
  <% if session[:user_id] %>
    <%= link_to "Log Out", logout_path, method: :delete %>

    <%= link_to "Your Profile", user_path(session[:user_id]) %>
    <br>
    <br>
   
  </div>
 <% end %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/podcasts/index.html.erb
<div>
  <h1>Welcome <%= (current_user.username).titleize if current_user %></h1>
</div>

<h2>Podcasts</h2>

<ul class="podcasts">
  <%= render @podcasts %>
</ul>

app/views/podcasts/most_recent.html.erb
<h2>Most Recent Podcasts</h2>

<% @podcasts.each do |podcast| %>
    <li><a href="<%= podcast_path(podcast)  %>"><%= podcast.name %></a> </li>
<% end %>

app/views/podcasts/new.html.erb
<h1> Upload a new Podcast! </h1>
<%= form_for(@podcast) do |f| %>

    
    <p> Select a Podcast that already exists </p>
    <div>
        <%=f.collection_select :id, Podcast.all, :id, :name, prompt: true %>
    </div>
    <p> Or Archive a New Podcast! </p>
   
    
            <%= f.label :name %>
            <%= f.text_field :name %>
            <%= f.label :author %>
            <%= f.text_field :author %>
            <%= f.label :description %>
            <%= f.text_area :description %>
            <%= f.label :category %>
            <%=f.collection_select :category_id, Category.all, :id, :name %>
    <%= f.submit %>



<% end %>

app/views/podcasts/show.html.erb
<h1><%= @podcast.name%>  </h1>


<h3><p> <%= @podcast.author%> </p></h3>
<div>
 <h4> <p><%= @podcast.description %></p></h4>
</div>





<br></br>

<%= link_to "See all Reviews", podcast_reviews_path(@podcast) %>
<%= link_to "Leave A Review",  new_podcast_review_path(@podcast) %>

app/views/reviews/index.html.erb
<h1> Reviews for <%= @podcast.name %> </h1>

<h4> <ul> <% @reviews.each do |review| %> 
    <li> <%= review.stars %> stars!
    <br>
    <%= review.description %>
    <br>
    <h3> Written by: </h3>
    <%= review.user.username %>
    </li>
    <br>
    <br>
    
    <% end %>

app/views/reviews/new.html.erb
<h1> Add a Review! </h1>


<%= form_for [@podcast, @review] do |f| %>
        <%= f.label :stars %>
        <%= f.number_field :stars, min:0, max:5 %>
        <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.hidden_field :podcast_id, value: @podcast.id %>

    <%= f.submit %>
    

<% end %>

app/views/users/new.html.erb
<h1> Sign Up! </h1>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>


    <%= f.submit "Sign Up" %> 

<% end %>

app/views/users/show.html.erb
<center><h1> Welcome, <%= @user.username %></h1></center>

<h3> Here's what you've listened to: </h3>

<ul>
<% Podcast.joins(:users_podcasts=>[:user]).where("users.id = ?", current_user.id).each do |podcast| %>
    <li><%= podcast.name %> </li>
 <% end %>

<br>
<br>



<%= link_to "Add a Podcast", new_podcast_path %>
<br>
<%= link_to "Podcast Categories", categories_path %>